// Íconos de módulos, menús y submenús: el backend guarda el nombre del ícono (p. ej.
// "faUsersGear") y aquí se resuelve a su definición de Font Awesome.
import {
  faArrowsTurnRight,
  faBoxesStacked,
  faCalculator,
  faCapsules,
  faCashRegister,
  faChartBar,
  faChartPie,
  faClipboardList,
  faDoorClosed,
  faDoorOpen,
  faFileContract,
  faFileInvoice,
  faFileInvoiceDollar,
  faFileMedical,
  faFlag,
  faHandHoldingMedical,
  faHeartPulse,
  faHospital,
  faHospitalUser,
  faInbox,
  faClipboardUser,
  faKitMedical,
  faMoneyBillWave,
  faNotesMedical,
  faPaperclip,
  faScrewdriverWrench,
  faShieldHeart,
  faStethoscope,
  faSyringe,
  faTags,
  faTruckMedical,
  faUserDoctor,
  faUserInjured,
  faUsersGear,
  faUserShield,
  faVials,
  faWallet,
  faWarehouse,
  faXRay,
  IconDefinition,
} from "@fortawesome/free-solid-svg-icons";

const NAV_ICONS: Record<string, IconDefinition> = {
  faClipboardUser: faClipboardUser,
  faStethoscope: faStethoscope,
  faXRay: faXRay,
  faVials: faVials,
  faUserDoctor: faUserDoctor,
  faArrowsTurnRight: faArrowsTurnRight,
  faTruckMedical: faTruckMedical,
  faBoxesStacked: faBoxesStacked,
  faCashRegister: faCashRegister,
  faInbox: faInbox,
  faBuildingHospital: faHospital,
  faHandshakeMedical: faHandHoldingMedical,
  faFileContract: faFileContract,
  faTags: faTags,
  faShieldHeart: faShieldHeart,
  faCapsules: faCapsules,
  faUsersGear: faUsersGear,
  faUserShield: faUserShield,
  faSyringe: faSyringe,
  faWarehouse: faWarehouse,
  faScrewdriverWrench: faScrewdriverWrench,
  faWallet: faWallet,
  faClipboardList: faClipboardList,
  faDoorOpen: faDoorOpen,
  faUserInjured: faUserInjured,
  faHeartPulse: faHeartPulse,
  faHospitalUser: faHospitalUser,
  faFileMedical: faFileMedical,
  faNotesMedical: faNotesMedical,
  faKitMedical: faKitMedical,
  faDoorClosed: faDoorClosed,
  faFileInvoice: faFileInvoice,
  faPaperclip: faPaperclip,
  faFileInvoiceDollar: faFileInvoiceDollar,
  faChartBar: faChartBar,
  faChartPie: faChartPie,
  faMoneyBillWave: faMoneyBillWave,
  faFlag: faFlag,
  faCalculator: faCalculator,
};

export const getNavIcon = (icon?: string | null): IconDefinition | undefined =>
  icon ? NAV_ICONS[icon] : undefined;
